# https://www.clouddev.engineering/deploying-a-container-in-an-azure-devops-pipeline/

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-18.04'
 
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'paybankregistry-CI-CD'
    repository: 'pay-bank-app'
